### ISSUE TITLE
AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'

### ISSUE THREAD

**Issue by lokender** [chaitanya100100/TailorNet#10]
Hi Chaitanya,

Can you please share the blender version you used in your work?. I am getting following error
AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'

**Comment by chaitanya100100** [comment]
It works with blender 2.79.

Blender renderer script is not used to run on its own. You need to call one of the functions like visualize_body, visualize_garment, etc with appropriate arguments.
These functions store meshes in a temporary location and then call blender with python script as an argument. The code is fairly easy to understand provided that you know how blender works with python script.

**Comment by lokender** [comment]
Thanks, Chaitanya, I figured that out. I
